theme: jekyll-theme-minimal

logo: /images/IMG_20170108_192039.jpg

title: Karl Kunze 

description: Plants | Breeding | Genetics | Barley | Cornell University        

github: is\_project\_page:false  


