theme: jekyll-theme-minimal

logo: https://github.com/karlkunze/karlkunze.github.io/master/blob/images/khk44.png

title: Karl Kunze 

description: Plants | Breeding | Barley | Cornell University        

github: is\_project\_page:false  

