theme: jekyll-theme-minimal

logo: /images/IMG_20170108_192039.jpg

title: Karl Kunze 





description: Interdisciplinary | Barley | Plants | Breeding | Genetics    

github: is\_project\_page:false  


