theme: jekyll-theme-minimal

logo: https://github.com/karlkunze/karlkunze.github.io/master/images/khk44.png?raw=true

title: Karl Kunze 

description:  Plants | Breeding | Genetics | Cornell University        

github: is\_project\_page:false  

