---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in
title: "Curriculum Vitae"
author: Karl Hans Kunze
address: "422 Bradfield Hall, Ithaca NY 14853"
fontawesome: yes
email: khk44@cornell.edu
linkedin: "karlkunze"
github: karlkunze
twitter: @kunzx37
#phone:
web: karlkunze.github.io
updated: no
keywords: Plant Breeding, Genetics, Quantative Genetics, Experimental Design, Barley
fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Current Position

PhD Candidate in Plant Breeding and Genetics, advisor Dr. Mark Sorrells, Cornell University       \hfill 2017-present

# Education:

B.S. Plant Science concentration in Plant Breeding and Genetics,
  minor in Business for Life Sciences- Cornell University             \hfill 2013-2017

# Experience

Graduate Research Assistant, Graduate School Field of Plant Breeding minor in Plant Pathology and Food Science, Cornell University \hfill 2017-present

# Research Projects

-   Weed Competitive Ability in Organic Spring Naked Barley and use collected field trait phenotypes and UAV imaging to measure barley vigor and growth in organic environments

-   Genetic by environmental analysis of winter organic naked barley variety trials across 3 years and 3 locations in the Northern United States

-   Genome wide association of of barley disease resistance across 18 location by year field trials of a naked barley diversity panels

-   Germination and malting quality analysis of winter barley breeding lines. Characterization of physiological maturity, pre-harvest sprouting, and dormancy breakage related to winter malting barley

- Production and development of the Cornell Small Grains winter malting barley breeding program

-   Conducted research the USDA ARS Cereal Crops Research Unit in Madison, WI in December 2021 and January-February 2022 to assist in malting quality analysis of a subset of NY malting barley lines.

-   Use aerial imaging to quantify winter barley growth rates to determine winter survival and yield quality

# Skills

-   Highly proficient in operating and data collection of a plant breeding program including recording field phenotypes, data management, using phenotype and genotype data for selection decisions, grain processing, analysis, organization, and experimental design of field trials
-   Highly proficient in R statistical software and Excel for data management and analysis 

-   Basic proficiency in Unix shell scripting and command line. Limited experience with Python

-   Certified FAA UAS Part 107 Remote Pilots License. 

-   Highly Proficient in flying unmanned aerial systems for imaging of plant variety trials and breeding populations. Have conducted over 100 aerial imaging flights

-   Basic proficiency in Agisoft Pro and Open Drone Map software stitching applications. Basic proficiency in Docker applications

-   Basic proficiency in chemistry malting quality analysis for alpha-amylase, diastatic power, beta-glucan, soluble wort protein and free amino nitrogen analysis

-   Demonstrated abilities to work in collaborative multi-institutional research projects

-   Co-led a weekly graduate student journal club with Will Stafstrom in the Spring 2022 semester. Topics were related to current research and topics in the fields of plant breeding, genetics and crop science

-   Participated in an International exchange workshop between Cornell University, Tokyo University of Agriculture and Technology and the Technical University of Munich \hfill October 2019

# Awards Received

-   Gerald O. Mott Award Recipient \hfill March 2022 

-   Cornell Plant Breeding and Genetics Munger-Murphy Award \hfill August 2022 

-   Recipient of the ASA, CSSA, SSSA Future Leaders in Science Award \hfill December 2018

# Grants and Fellowships

-   Developing Multi-use Naked Barley for Organic Farming Systems I & II: USDA-NIFA-OREI Grant 2017-51300-26809

-   American Malting Barley Association Grant 2020-2021: Genetic Characterization of Germination Traits and Their Relationship to Preharvest Sprouting in Winter and Spring Barley 

-   American Malting Barley Association Grant 2021-2022: Germination Traits & Relationships to Pre-Harvest Sprouting

-   NYS Department of Agriculture and Markets Funding

# Publications \orcidlink{0000-0003-4548-1808}

1. Massman, C., Meints, B., Hernandez, J., Kunze, K., Smith, K. P., Sorrells, M. E., ... & Gutierrez, L. Genomic prediction of threshability in naked barley. Crop Science. <https://doi.org/10.1002/csc2.20907>

2.  Travis E. Rooney, Karl H. Kunze, Mark E. Sorrells. The Plant Genome(2022) Genome wide marker effect heterogeneity is associated with a large effect dormancy locus in winter malting barley. <https://doi.org/10.1002/tpg2.20247>

3. Bunting, J. S., Ross, A. S., Meints, B. M., Hayes, P. M., Kunze, K.,& Sorrells, M. E. (2022). Effect of Genotype and Environment on Food-Related Traits of Organic Winter Naked Barleys. *Foods*, *11*(17),2642.<https://doi.org/10.3390/foods11172642>

4.  Chris Massman, Brigid Meints, Javier Hernandez, Karl Kunze, Patrick M.Hayes, Mark E. Sorrells, Kevin P. Smith, Julie C. Dawson, and Lucia Gutierrez. Crop Science(2022) Genetic Characterization of Agronomic Traits and Grain Threshability for Organic Naked Barley in the Northern U.S. <https://doi.org/10.1002/csc2.20686>

5. Sweeney, D.W., Kunze, K.H. & Sorrells, M.E. QTL x environment modeling of malting barley preharvest sprouting. Theor Appl Genet (2021). <https://doi.org/10.1007/s00122-021-03961-5>

# Professional Services 
-   Student representative of the CSSA(Crop Science Society of America) executive board     \hfill 2022-2023

-   Representative of the CSSA science policy committee \hfill 2022-present 

-   Local Graduate Student Liaison representative and member for the National Association of Plant Breeders (NAPB) Graduate Student Working Group \hfill Fall 2020- August 2021 

-   Cornell Plant Breeding and Genetics Graduate Student Association Synapsis-Professional Development Committee Member      \hfill 2020-2021 

-   Corteva Symposium organizing committee member \hfill Fall 2018-April 2019 

-   Graduate Student Representative on the 2019 Cornell Plant Breeding Faculty Search Committee    \hfill Spring 2019

-   Cornell Plant Breeding and Genetics Graduate Student Association, Synapsis-President \hfill 2018-2019 

-   Plant Breeding Field representative for the Cornell Graduate and Professional Student Association \hfill 2017-2019

-   Graduate student representative on the Cornell University, College of Agriculture and Life Sciences alumni committee \hfill 2018-present

# Professional Societies

-   Tri societies CSSA(Crop Science Society of America) student member \hfill 2019-present 

-   National Association of Plant Breeders (NAPB) student member \hfill 2020-present 

-   New York State Agriculture Society member \hfill 2017-present

-   Student Organic Seed Society member\hfill 2020-2021 

-   Alumni of Alpha Gamma Rho, Zeta Chapter-Cornell University

# Presentations and Conferences attended

<<<<<<< HEAD
- Presented research and updates on winter malting barley variety development at the 5th annual Empire State Malting Barley Summit at the Culinary Institute of America December 2022, Hyde Park, New York
=======
-Presented the progress of winter malting barley breeding in New York at the New York State Empire Malting Barley summit at the Cullinary Institute of America Hyde Park, NY \hfill December 2022
>>>>>>> 39d5ba947de90f6edf69cc7b410d95f873e3f04a

- Research Presentations titled "Interaction of Pre-harvest sprouting, germination rate and malting quality for winter and facultative malting barley" and "Genotype by Environment Interaction of Organic Winter Naked Barley" at CSSA,ASA and SSSA Tri-society annual meeting November 2022, Baltimore, Maryland

-   Research Presentation titled "Interaction of Pre-harvest sprouting, germination rate and malting quality for winter and facultative malting barley" at the 23rd North American Barley Researchers Workshop and 43rd Barley Improvement Conference September 2022, UC Davis,CA

-   Research Presentation titled "Developing Winter Malting Barley for New York State" Michigan Beer and Malt Conference January 2022 Traverse City, MI 

-   Research Presentation titled "Components of Weed Competitive Ability" at CSSA,ASA and SSSA Tri-society annual meeting November 2021, Salt Lake City, Utah 
-   Presented eOrganic Webinar Titled "Progress on Organic Naked Barley Breeding, Exploration of Organic Breeding Traits" April 2021 
-   Presenter at the Philly Malt and Grains Conference, Virtual March 2021 
-   Attended Student Organic Seed Society (SOSS) conference- Madison, WI, August 2019 
-   Participant in the Tri-societies poster competition Baltimore, MD, November 2018 Attended NOFA-NY Organic Conference January 2018
