---
title: "Résumé, Academic"
author: "Karl Hans Kunze, PhD"
date: "04/05/2026"
output: 
  pdf_document:
    latex_engine: xelatex
    keep_tex: true
    dev: cairo_pdf
    template: template.tex
orcidlink: TRUE
fontawesome: TRUE
# How can we get a hold of you?
email: karl.kunze13@gmail.com
#phone: 
location: "9241 Mace Blvd. Davis, CA 95618"
github: karlkunze
web: karlkunze.github.io
linkedin: "karlkunze"
orcid: "0000-0003-4548-1808"
geometry: "top=.25in, left =.25in, right=.25in, bottom=.5in"
update: yes
mainfont: cochineal
sansfont: Fira Sans
monfont: Fira Sans
# monofont: Fira Code # I want to use this, but seems to choke on @
urlcolor: blue
fontsize: 11pt

includephoto: FALSE
myphoto: /home/karl/git/karlkunze.github.io/images/khk44_2017.jpg
# shift: "7in,-.25in" # this is default
photobigness: 1.75cm
# photozoom: ".2\textwidth" # this is default
---

<!-- Read more about Pandoc's [fenced_divs](https://pandoc.org/MANUAL.html#extension-fenced_divs) syntax -->

:::::: {.columns}
::: {.column width="48%" data-latex="{0.48\textwidth}"}

# Current Position

- Hot Pepper Breeder I, HM Clause/Limagrain, Davis, CA 
  \hfill\mbox{March 2024 - present}
  
# Past Position

- Post Doctoral Researcher, advisor Dr. Kelly Robbins, Cornell University, Ithaca NY
  \hfill\mbox{June 2023 - Feb 2024}

# Education

## Graduate

- Cornell University, Graduate School, Ithaca, NY, PhD Plant Breeding, Advisor Dr. Mark Sorrells
\hfill\mbox{Aug 2017- May 2023}
    - Dissertation title "Genomic And Phenotypic Characterization of Malting Barley and Naked Multi-use Barley as Winter Crops for New York State"
   
## Undergraduate

-   Cornell University, College of Agriculture and Life Sciences, Ithaca, NY, Bachelor of Science Plant Sciences
  \hfill\mbox{Aug 2013 - May 2017}

-  Wageningen University and Research, Wageningen, Netherlands, Student Exchange Program 
\hfill\mbox{Jan 2016 - May 2016}

# Technical Skills

-   Highly proficient in operating and data collection of a 

-   Highly proficient of conceptualization, management and logistical implementation of academic and industry plant breeding proagrams.

-   Highly experienced in processing, analysis, organization, and experimental design for barley and hot pepper breeding systems, Highly experienced in modeling with novel statistical concepts including linear mixed models, random regression and longitudinal measurements for hot pepper open field and barley.

-   Highly proficient in R statistical software for data management and analysis. Moderate proficiency in using git version control, command line, and image stitching applications. Basic experience with Python, Docker, and html

-   Experienced in flying unmanned aerial systems for imaging of plant variety trials and breeding populations & Certified FAA UAS Part 107 Remote Pilots License.

# Leadership Activities and Professional Services

- Graduate Student representative of the Crop Science Society of America (CSSA) executive board & Science policy committee  \hfill {2022-present}

- Cornell Plant Breeding and Genetics Graduate Student Association(Synapsis)-President and Graduate student representative on a faculty search committee 
          \hfill\mbox{Nov 2018 - Apr 2019}


:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
 <!-- an empty div with an empty character to serve as a column sep -->
 \ 
:::
::::::  {.column width="44%" data-latex="{0.44\textwidth}"}
# Experience

## Statisical modeling of alfalfa growth using multi-spectral aerial imaging

- Performed logistical and data management of multi-spectral imaging of 4 alfalfa locations, from stitching to image value extraction

- Used novel statistical methods such as random regression and spatial analysis to model alfalfa growth curves using extracted NDVI values as a proxy for ground truth biomass

- Experience using open source database breeding software such as Imagebreed and Breedbase and interfacing with software developers

## Management of a winter malting barley breeding program for New York State

-   Advanced a double haploid and recombinant inbred population starting with crosses in 2017. Currently testing 25 lines for a third year of yield trials and a preliminary yield trial consisting of 200 advanced double haploid lines and 200 recombinant inbred lines.

- Conducted an extensive seed dormancy assay experiment over two years to determine dormancy loss in a winter malting breeding population. A total of 450 lines were measured at 3 locations over two years, and an average of 5 timepoints per year were conduced
 
-   Micro malted 240 winter barley  over two time points at the USDA Cereal crops and research unit in Madison, WI. Malting quality resulted were used to inform selection decisions \hfill\mbox{Dec 2021 and Jan-Feb 2022}

-   Used genomic prediction, linear mixed models, spatial correction and genome wide association studies to advance lines and inform selection decisions

## Organic Multi-use naked barley for New York and the Northern United States

- Performed genotype by environment analysis for eight naked barley trials across the northern United States

- Performed a genome wide association analysis of 250 diverse barley lines across 13 environments for foliar disease resistance in natural field organic conditions

- Used aerial imaging of a spring naked barley variety trial over two years to quantify barley growth over time as a precursor for competition with weeds.

- Initialized a combined nested association population using three common parents across all collaborating institution and five parents specific to NY conditions.

:::
:::::

\newpage

:::::: {.columns}
::: {.column width="44%" data-latex="{0.44\textwidth}"}

# Awards and Grants Received

-  Graduate student of USDA OREI grants program "Developing Multi-use Naked Barley for Organic Systems I, II and III"

-   Genetic Characterization of Germination Traits and Their Relationship to Preharvest Sprouting in Winter and Spring Barley, award of $11,500- American Malting barley Association Grant Award \hfill\mbox{July 2021-June 2022}

- Cornell Plant Breeding and Genetics Munger-Murphy Award \hfill {Aug 2022}

- CSSA Gerald O. Mott Award Recipient \hfill {March 2022}

- Recipient of the ASA, CSSA, SSSA Future Leaders in Science Award \hfill {Dec 2018}

# Professional Societies

- Crop Science Society of America (CSSA) student member \hfill {2019-2024}

- National Association of Plant Breeders (NAPB) student member \hfill {2020-2024}

- New York State Agriculture Society member \hfill {2017-2024}

- Cornell Plant Breeding and Genetics Graduate Student Association, Synapsis \hfill {2017-2023}

- Alumni of Alpha Gamma Rho, Professional and Social Agricultural Fraternity, Zeta Chapter

# Selected Publications
1. Kunze, K. H., Rooney, T. E., Sweeney, D., & Sorrells, M. E. (2026). The SD1 locus affects primary seed dormancy in winter malting barley. The Plant Genome, 19, e70234. <https://doi.org/10.1002/tpg2.70234>

2. Kunze, K. H., Meints, B., Massman, C., Gutiérrez, L., Hayes, P. M., Smith, K. P., Bergstrom, G. C., & Sorrells, M. E. (2024). Genome-wide association of an organic naked barley diversity panel identified quantitative trait loci for disease resistance. The Plant Genome, 17, e20530. <https://doi.org/10.1002/tpg2.20530>

3. Kunze, K. H., Meints, B., Massman, C., Gutiérrez, L., Hayes, P. M., Smith, K. P., & Sorrells, M. E. (2024). Genotype × environment interactions of organic winter naked barley for agronomic, disease, and grain quality traits. Crop Science, 64, 678–696. https://doi.org/10.1002/csc2.21195

4. Ranjita Thapa, Karl H Kunze, Julie Hansen, Christopher Pierce, Virginia Moore, Ian Ray, Liam Wickes-Do, Nicolas Morales, Felipe Sabadin, Nicholas Santantonio, Michael A Gore, Kelly Robbins, Remote sensing for estimating genetic parameters of biomass accumulation and modeling stability of growth curves in alfalfa, G3 Genes|Genomes|Genetics, Volume 14, Issue 11, November 2024, jkae200, <https://doi.org/10.1093/g3journal/jkae200>

5. Bunting, J. S., Ross, A. S., Meints, B. M., Hayes, P. M., Kunze, K.,& Sorrells, M. E. (2022). Effect of Genotype and Environment on Food-Related Traits of Organic Winter Naked Barleys. *Foods*, *11*(17),2642.<https://doi.org/10.3390/foods11172642>


:::
::: {.column width="2%" data-latex="{0.02\textwidth}"}
\ 

 <!-- an empty div with an empty character to serve as a column sep -->
:::

::: {.column width="50%" data-latex="{0.50\textwidth}"}

# Outreach

-   Virtual presentation with the Cornell Cooperative Extension of titled "Everything home gardeners want to ask about plant breeding" \hfill {March 2023}

-   Interviewed with the Craft Maltsters guild on [Breeding Malting Barley for New York State](https://craftmalting.com/field-to-bench-consumers-and-collaboration-spur-progress-in-barley-breeding-at-cornell-university/) \hfill {Feb 2023}

-   Presented on winter malting barley breeding progress for New York at the New York State Empire malting barley summit at the Culinary Institute of America, Hyde Park, NY           \hfill {Dec 2022}

-   Co-led a weekly graduate student journal club with Dr.Will Stafstrom. Topics were related to current research and topics in the fields of plant breeding, genetics and crop science.                     \hfill\mbox{Spring 2022} 
-   Wrote a brief article titled growing malting barley amid climate change for the [American Malting Barley Association](https://ambainc.org/news-details.php?id=63d014dfba04a)       \     \hfill {Sept 2022}

-   Guest on the ["All Things Agriculture Podcast"](https://www.youtube.com/watch?v=Dw_8N39wyBI) with Eric Carey 

- Participant in a Multi cultural exchange workshop Cornell University, Tokyo University of Agriculture and Technology and the Technical University of Munich   \hfill {Oct 2019}


# Research and Conference presentations

-   Hosted a panel of early career scientists from industry, non-profit and academia to discuss and answer questions regarding their experiences to graduate students and post-docs at the CSSA annual meeting in St. Louis, Missouri  \hfill {Oct 2023}

-   Presented current research and status of the NY winter malting barley project at the NYS Empire Malt and Barley Summit at the Culinary Institute of America, Poughkeepsie, NY \hfill {Dec 2022}

-   Presented research of "Interaction of Pre-harvest sprouting, germination rate and malting quality for winter and facultative malting barley" and "Genotype by Environment Interaction of Organic Winter Naked Barley" at CSSA annual meeting in Baltimore, Maryland     \hfill {Nov 2022}

-   Presented research of "Interaction of Pre-harvest sprouting, germination rate and malting quality for winter and facultative malting barley" at the 23rd North American Barley Researchers Workshop and 43rd Barley Improvement Conference UC Davis, CA 
\hfill {Sept 2022}

-   Presented research of "Developing Winter Malting Barley for New York State" Michigan Beer and Malt Conference in Traverse City, MI     \          \hfill {January 2022}

:::
:::
